### PR TITLE
Arm64 fdt support

### PR DESCRIPTION
**Pull request by guoweikang**
axhal/platfrom: Integrate platform code for axhal on the aarch64 architecture

--------
1. remove dw_apb_uart and pl011 uart code,abstract as aarch64 console
   trait;
2. remove bst,virt,raspi mem.rs, abstract as aarch64_common mem.rs
3. axhal add platform_name method
4. support arm  device tree

### CODE REVIEW

**Comment by elliott10** [comment]
1. dw_apb_uart and pl011 uart driver are low-level hardware related crates, and can be called by OS,  but should not be directly dependent on specific components of arceos.

 2. The addition of the device tree feature, I suggests submitting a separate PR.

**Comment by guoweikang** [comment]
> 1. dw_apb_uart and pl011 uart driver are low-level hardware related crates, and can be called by OS,  but should not be directly dependent on specific components of arceos.
In fact, I anticipate that future UART drivers will be abstracted as a serial driver, with "dw_apb" or "pl011" serving as driver features. In this commit, I have taken a straightforward approach to abstract them as a UartDriver ops(it is uglly now).
> 2. The addition of the device tree feature, I suggests submitting a separate PR.
Regarding the addition of the device tree feature, I agree with your suggestion of submitting a separate pull request (PR). I will indeed submit a distinct PR for that.

**Comment by scPointer** [comment]
主要是一些小的规范问题

### [scripts/make/qemu.mk](https://github.com/Arceos-monolithic/Starry/pull/1/files/0036083072875fac4f57c5f556ff79e22be8317d#diff-a5b579cc4d33f088805896250c55b0555c094d694628f25454320540db55a0e2)

配置文件不建议改动

### [README.md](https://github.com/Arceos-monolithic/Starry/pull/1/files/0036083072875fac4f57c5f556ff79e22be8317d#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

需要给更详细一点的说明：比方说现在新增命令是只能在板子上运行？还是可以在 qemu 上模拟运行？

### [crates/of/Cargo.toml](https://github.com/Arceos-monolithic/Starry/pull/1/files/0036083072875fac4f57c5f556ff79e22be8317d#diff-04d85cde9b864ecfce28dbeb4ec645c619dfa1b9241b4f8c9ff9a56d93d6d58f)

crate 名太短了，如果它是某种缩写，建议写全

### [crates/page_table_entry/src/arch/aarch64.rs](https://github.com/Arceos-monolithic/Starry/pull/1/files/0036083072875fac4f57c5f556ff79e22be8317d#diff-b8228da6fc32640050469c3396e7805d60b5cf69d5eda0f44ccf12f76da2b1ac)

使用 GenericPTE 的 is_unused，而不是单独为 A64PTE 实现一个重复的 is_empty。尽管这可能要在 `modules/axhal/src/platform/aarch64_common/mem.rs` 引入额外的 GenericPTE，但完全相同的函数太冗余了。

### [modules/axhal/src/platform/aarch64_common/boot.rs](https://github.com/Arceos-monolithic/Starry/pull/1/files/0036083072875fac4f57c5f556ff79e22be8317d#diff-8be11b3da5ded4368ab0988a4c4c183237920d75085613cb05992eb864d80bde)

所有变量加 `MY_` 是否是有特殊理由，还是只是命名习惯？如果没有，建议去掉它，然后把后面的缩写写全。

### [crates/of/tests/of.rs](https://github.com/Arceos-monolithic/Starry/pull/1/files/0036083072875fac4f57c5f556ff79e22be8317d#diff-9e553800376227a687785fd7ba293041bf1d383fe3eb3dd43176de7832fc844e)

同理，不需要 `MY_` 前缀，可以把 DTB 写全或者改叫 DTB_FILE 、DTB_DATA 、DTB_TEXT 之类的名字

### [modules/axruntime/src/lib.rs](https://github.com/Arceos-monolithic/Starry/pull/1/files/0036083072875fac4f57c5f556ff79e22be8317d#diff-557a9ff9346af8506692e25351145816cb1ca3e3ba51aaf288a37325d920bb9e)

打印输出直接写 `info!("Platform Name: {} ", axhal::platform_name());` 和代码保持一致。我没有找到 Machine Model 的这个概念。

**Comment by guoweikang** [comment]
> 主要是一些小的规范问题
> 
> ### [scripts/make/qemu.mk](https://github.com/Arceos-monolithic/Starry/pull/1/files/0036083072875fac4f57c5f556ff79e22be8317d#diff-a5b579cc4d33f088805896250c55b0555c094d694628f25454320540db55a0e2)
> 配置文件不建议改动
> 
> ### [README.md](https://github.com/Arceos-monolithic/Starry/pull/1/files/0036083072875fac4f57c5f556ff79e22be8317d#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
关于这个问题的详细原因，在[issue ](https://github.com/Azure-stars/Starry/issues/36) 有说明
> 需要给更详细一点的说明：比方说现在新增命令是只能在板子上运行？还是可以在 qemu 上模拟运行？
>
> ### [crates/of/Cargo.toml](https://github.com/Arceos-monolithic/Starry/pull/1/files/0036083072875fac4f57c5f556ff79e22be8317d#diff-04d85cde9b864ecfce28dbeb4ec645c619dfa1b9241b4f8c9ff9a56d93d6d58f)
好
> crate 名太短了，如果它是某种缩写，建议写全
> 
> ### [crates/page_table_entry/src/arch/aarch64.rs](https://github.com/Arceos-monolithic/Starry/pull/1/files/0036083072875fac4f57c5f556ff79e22be8317d#diff-b8228da6fc32640050469c3396e7805d60b5cf69d5eda0f44ccf12f76da2b1ac)
此命名方式 借鉴 linux中的  `Open Firmware` 开放的硬件描述和配置标准的缩写 
> 使用 GenericPTE 的 is_unused，而不是单独为 A64PTE 实现一个重复的 is_empty。尽管这可能要在 `modules/axhal/src/platform/aarch64_common/mem.rs` 引入额外的 GenericPTE，但完全相同的函数太冗余了。
>
> ### [modules/axhal/src/platform/aarch64_common/boot.rs](https://github.com/Arceos-monolithic/Starry/pull/1/files/0036083072875fac4f57c5f556ff79e22be8317d#diff-8be11b3da5ded4368ab0988a4c4c183237920d75085613cb05992eb864d80bde)
OK 
> 所有变量加 `MY_` 是否是有特殊理由，还是只是命名习惯？如果没有，建议去掉它，然后把后面的缩写写全。
> 
> ### [crates/of/tests/of.rs](https://github.com/Arceos-monolithic/Starry/pull/1/files/0036083072875fac4f57c5f556ff79e22be8317d#diff-9e553800376227a687785fd7ba293041bf1d383fe3eb3dd43176de7832fc844e)
> 同理，不需要 `MY_` 前缀，可以把 DTB 写全或者改叫 DTB_FILE 、DTB_DATA 、DTB_TEXT 之类的名字
> 
> ### [modules/axruntime/src/lib.rs](https://github.com/Arceos-monolithic/Starry/pull/1/files/0036083072875fac4f57c5f556ff79e22be8317d#diff-557a9ff9346af8506692e25351145816cb1ca3e3ba51aaf288a37325d920bb9e)
> 打印输出直接写 `info!("Platform Name: {} ", axhal::platform_name());` 和代码保持一致。我没有找到 Machine Model 的这个概念。
Machine Model  同上，借鉴设备树关于设备描述的标准术语，这里确实没有一致，应该是 Machine Model，这里显示为Platform Name 的一部分原因是 porting  ArceOS的 platform 的术语

**Comment by scPointer** [comment]
:+1:
- 关于 issue 的问题：至少还是要在 README 指出“在 aarch64 上默认启动 qemu 时内存大小不同” 以及原因。
- `MY_` 目前还没看到回复或者修改

**Comment by guoweikang** [comment]
> 👍
> 
> * 关于 issue 的问题：至少还是要在 README 指出“在 aarch64 上默认启动 qemu 时内存大小不同” 以及原因。
> * `MY_` 目前还没看到回复或者修改

**Comment by guoweikang** [comment]
This PR will split with

**Pull request merged**
